eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8083
  
spring:
  application:
    name: EUREKA_CLIENT-2